
// Standard causes list for not completed tasks
export const standardCauses = [
  "Absenteísmo",
  "Atraso",
  "Chuva",
  "Executante produzindo abaixo do planejado",
  "Executante trabalhando em outra obra",
  "Erro no planejamento",
  "Falta de comunicação",
  "Falta de equipamento",
  "Falta de liberação dos espaços",
  "Falta de mão de abra (atraso na contratação)",
  "Falta de mão de obra",
  "Falta de material",
  "Falta de planejamento de compra",
  "Falta de projeto",
  "Indefinição Engenharia",
  "Material distribuido em quant. Insuficiente",
  "Material incorreto",
  "Material solicitado em qt insuficiente",
  "Mau dimensionamento do executante",
  "Modificação de projeto",
  "Monitoramento de quant. de material em estoque",
  "Mudança do plano de ataque",
  "Pacote de trabalho grande",
  "Predecessora concluída fora de prazo",
  "Presença de água",
  "Quebra/Manutenção de equipamento",
  "Relocação da mão de obra",
  "Retrabalho",
  "Sem disponibilidade",
  "Vento",
  "Outros"
];
