// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qacaerwosglbayjfskyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhY2Flcndvc2dsYmF5amZza3l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDEwNDksImV4cCI6MjA2MjgxNzA0OX0.gT9Je1R7Kv-UTJLV0C9K9UA5tfdTr3leB7Dp8NCDQK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});